#include <sys/socket.h>
#include <sys/types.h>
#include <syslog.h>
#include <string.h>
#include <stdio.h>
#include <netdb.h> 
#include <stdlib.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <sys/stat.h>
#include <signal.h>